image: docker:latest

stages:
- build
- test
- docker
- deploy

build:
  image: maven:3-openjdk-17
  stage: build
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar

test:
  image: maven:3-openjdk-17
  stage: test
  script:
    - mvn test

docker:
  stage: docker

  services:
  - docker:dind

  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  
  dependencies:
  - test
  
  script:
    - docker build -t $CI_DOCKER_USER/api-order-teste -f Dockerfile .
    - docker push $CI_DOCKER_USER/api-order-teste

deploy:
  stage: deploy
  script:
    - echo "Deploying Application..."
    - echo "Application successfully deployed!"


