image: yhaohannah/ubuntu-maven-java

stages:
- build
- test
- docker
- deploy

build:
  stage: build
  script:
    - java -jar ./target/api.orders-0.0.1-SNAPSHOT.jar

test:
  stage: test
  script:
    - mvn test

# docker:
#   image: docker:19.03.0

#   services:
#   - docker:dind

#   before_script:
#     - docker info
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  
#   stage: docker

#   dependencies:
#     - test
  
#   script:
#     - echo "Creating image docker..."
#     - ocker build -t $CI_DOCKER_USER/api-order-teste -f Dockerfile .
#     - echo "Uploading image to docker hub..."
#     - docker push $CI_DOCKER_USER/api-order-teste

# deploy:
#   stage: deploy
#   script:
#     - echo "Deploying Application..."
#     - 
#     - echo "Application successfully deployed!"


